### ISSUE TITLE
png turned off

### ISSUE THREAD

**Issue by stact** [tomwyr/avataaar-image#12]
Hi guys 

Unfortunatelly avataars.io turned off png: https://github.com/gkoberger/avataaars/issues/16

Maybe could we enable flutter_svg (https://pub.dev/packages/flutter_svg)? Or allow custom api base url? Or both?

Hope that news will not break any existing apps.
Current error `exception could not instantiate image codec`

**Comment by tomwyr** [comment]
Thanks for posting this issue, I wasn't aware of PNGs being turned off. This is really unfortunate.
I think both your ideas would make the package more flexible. Do you have any experience with `flutter_svg`, how well does it handle rendering more complex vector images? I've never worked with this pacakge. @stact

**Comment by stact** [comment]
@tomwyr I've tested the lib `flutter_svg` not working with complex vector images

```dart
    final Widget networkSvg = SvgPicture.network(
      'https://avataaars.io',
      // 'https://dev.w3.org/SVG/tools/svgweb/samples/svg-files/410.svg',
      semanticsLabel: 'A shark?!',
      placeholderBuilder: (BuildContext context) => Container(
          padding: const EdgeInsets.all(30.0),
          child: const CircularProgressIndicator()),
    );

    return Container(color: Colors.blueGrey, child: networkSvg,);
```

**Comment by tomwyr** [comment]
I've also tried to use it with avataaars images and it seems to work pretty well except one thing. If `avatarStyle` is set to `Transparent` [like here](https://avataaars.io/?avatarStyle=Transparent), then svg code references a mask layer (*mask-4* specifically) that's not defined and `flutter_svg` throws an exception during rendering the image.

I created an [issue](https://github.com/dnfield/flutter_svg/issues/410) on `flutter_svg` repo asking to allow missing masks to be ignored.

**Comment by gkoberger** [comment]
Sorry about that, it was costing a few thousand dollars and people were spamming it! The code still works if you want to host it yourself :)

**Comment by tomwyr** [comment]
@gkoberger Sure thing, this is totally understandable (few thousand dollars this is crazy). I think supporting SVGs and API custom url is the way to go.

**Comment by tomwyr** [comment]
I decided to fork `flutter_svg` and fix error-causing behavior for some avatars. You can depend on git version of the package for now and see if this work for you.

**Comment by stact** [comment]
i'm trying to resolve:
```
pub get failed (server unavailable) -- attempting retry 1 in 1 second...
Git error. Command: `git clone --mirror git@github.com:tomwyr/flutter_svg.git
[...]
Host key verification failed.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
exit code: 128
```

I let u know

**Comment by stact** [comment]
On windows:

Git bash
``` powershell
git config --global user.name "John Doe"
git config --global user.email "johndoe@doebrothers.com"
ssh-keygen -t rsa -C "johndoe@doebrothers.com"
# to not be prompted
eval $(ssh-agent)
ssh-add ~/.ssh/id_rsa
# read pub file and copy/paste on github setting (add ssh)
cat ~/.ssh/id_rsa.pub
```

**Comment by tomwyr** [comment]
My bad, I set forked repo in pubspec with ssh url.
Could you try again now? @stact

**Comment by stact** [comment]
It's working but got some color issue:
My app:
![image](https://user-images.githubusercontent.com/9899166/93137759-4809dd00-f6de-11ea-8209-2d1bfd2b44c5.png)

vs.

Avataaars.io
![image](https://user-images.githubusercontent.com/9899166/93137831-6374e800-f6de-11ea-9a23-35158599af13.png)

Source code:
``` dart
AvataaarImage(
        avatar: Avataaar(top: Top.longHairBob(hairColor: HairColor.Platinum, facialHair: FacialHair.beardMagestic(facialHairColor: FacialHairColor.Platinum))),
        placeholder: CircularProgressIndicator(),
      )
```

**Comment by stact** [comment]
Got error on random image:

``` dart
AvataaarImage(
        avatar: Avataaar.random(
          skin: Skin.pale,
          style: Style.circle,
          top: Top.longHairCurly(
            accessoriesType: AccessoriesType.Round,
            facialHair: FacialHair.random,
          ),
        ),
        placeholder: CircularProgressIndicator(),
      )
```
```
I/flutter (10655): unhandled element filter; Picture key: NetworkPicture("https://avataaars.io/?topType=LongHairCurly&accessoriesType=Round&facialHairType=BeardMagestic&facialHairColor=BrownDark&clotheType=ShirtScoopNeck&clotheColor=Gray01&eyeType=Close&eyebrowType=UpDown&mouthType=Twinkle&skinColor=Pale&avatarStyle=Circle", headers: null, colorFilter: null)
```

**Comment by stact** [comment]
@tomwyr it seems that flutter_png removing some effects ^^
I will try to find the reason

**Comment by stact** [comment]
@tomwyr seems to be related to https://github.com/dnfield/flutter_svg/issues/307

**Comment by tomwyr** [comment]
Thanks for linking the issue you've found. Apparently `flutter_svg` is not capable of parsing all svg attributes that are present in avataaars images.
