### ISSUE TITLE
It is loading forever in the stateless 

### ISSUE THREAD

**Issue by dlpigpen** [tomwyr/avataaar-image#13]
In the BuildContext block i set a variable:  var _avatar = Avataaar.random();
then i loaded it into the ClipRect:
`ClipRRect(
                borderRadius: BorderRadius.all(Radius.circular(15.0)),
                child: AvataaarImage(
                  avatar: _avatar,
                  errorImage: Icon(Icons.error),
                  placeholder: CircularProgressIndicator(),
                  width: 128.0,
                ),
              ),`
Unluckily it is loading forever, http and https have beeen allowed.

**Comment by tomwyr** [comment]
Images currently don't load because avataaars.io disabled PNG support. See #12 .
