### ISSUE TITLE
Upgrade cached_network_image package

### ISSUE THREAD

**Issue by benoitverstraete** [tomwyr/avataaar-image#2]
Hi,

Could you please upgrade the package cached_network_image in yours ? The last version is 0.8.0 while yours is 0.7.0.

Thanks a lot !

**Comment by tomwyr** [comment]
It's now dependent on cached_network_image 0.8.0. Current version of the package is 1.0.4.
Thanks for letting me know.

**Comment by inquisiteur** [comment]
Hi, there is a breaking change on cached_network_image making your package unusable.

> Breaking change with ImageProvider.load in Flutter 1.10

The Flutter team made a breaking change with the ImageProvider in Flutter 1.10.15 (currently Master channel only).

If you are experiencing one of the following errors upgrade to 2.0.0-rc.
