### ISSUE TITLE
Can we get cached_network_image updated to the latest release

### ISSUE THREAD

**Issue by Paul-Todd** [tomwyr/avataaar-image#7]
Hi,

Can you update the dependencies to the latest release?

Paul

**Comment by tomwyr** [comment]
Hi there

checkout the latest version - it is now dependent on `cached_network_image` 1.1.1.

**Comment by inquisiteur** [comment]
Hi, can you update the dependencies to the latest release ? 

Serge

**Comment by tomwyr** [comment]
I'll update the package later today.

**Comment by tomwyr** [comment]
@inquisiteur You can update package version to 1.0.7.

**Comment by inquisiteur** [comment]
Thanks 😊

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
