### ISSUE TITLE
Option to choose the gender of the avatar

### ISSUE THREAD

**Issue by rodrigobastosv** [tomwyr/avataaar-image#8]
I would really appreciate if we have the option to choose the gender of the avatar, so we can for example in a listview of people give appropriate avatar to men and women .

**Comment by tomwyr** [comment]
Actually the avataaars api doesn't make such a distinction so there's nothing I can do about it. It's just one's perception that makes a character look more like a man/woman.

E.g. [this](https://getavataaars.com/?accessoriesType=Prescription02&avatarStyle=Circle&clotheColor=Blue03&clotheType=ShirtVNeck&eyeType=Hearts&eyebrowType=UpDown&facialHairColor=Black&facialHairType=BeardMedium&graphicType=Hola&hairColor=Blonde&hatColor=Heather&mouthType=Tongue&skinColor=Tanned&topType=LongHairFro) and [this](https://getavataaars.com/?accessoriesType=Prescription02&avatarStyle=Circle&clotheColor=Blue03&clotheType=ShirtVNeck&eyeType=Hearts&eyebrowType=UpDown&facialHairColor=Black&facialHairType=Blank&graphicType=Hola&hairColor=Blonde&hatColor=Heather&mouthType=Tongue&skinColor=Tanned&topType=LongHairFro) avatars are exactly the same except for their facial hair.

**Comment by tomwyr** [comment]
You could check whether the avatar has long/short hair or facial hair and assume its gender depending on that but this probably won't be 100% accurate.
